# Generated by Django 5.2.6 on 2025-09-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Keeper", "Goalkeeper"),
                            ("Defender", "Defender"),
                            ("Midfielder", "Midfielder"),
                            ("Attacker", "Attacker"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("elo", models.FloatField(help_text="Player's Elo rating")),
                ("cost", models.FloatField(help_text="Player's cost in millions")),
                (
                    "week",
                    models.IntegerField(db_index=True, help_text="Game week number"),
                ),
                ("team", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "competition",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "players",
                "ordering": ["-elo"],
                "indexes": [
                    models.Index(
                        fields=["week", "position"], name="players_week_bd87d3_idx"
                    ),
                    models.Index(
                        fields=["week", "elo"], name="players_week_bdf28c_idx"
                    ),
                    models.Index(
                        fields=["position", "elo"], name="players_positio_5b0a51_idx"
                    ),
                ],
                "unique_together": {("name", "week")},
            },
        ),
    ]
