# Generated by Django 5.2.6 on 2025-09-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0003_elocalculation_playermatch"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CurrentSquad",
        ),
        migrations.DeleteModel(
            name="EloCalculation",
        ),
        migrations.DeleteModel(
            name="Player",
        ),
        migrations.DeleteModel(
            name="PlayerMatch",
        ),
    ]
