# Generated by Django 5.2.6 on 2025-09-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrentSquad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Current Squad", max_length=100)),
                ("squad_data", models.TextField(default="{}")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "current_squad",
            },
        ),
        migrations.CreateModel(
            name="EloCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(db_index=True, max_length=200)),
                ("week", models.IntegerField(db_index=True)),
                ("season", models.CharField(max_length=20)),
                ("elo", models.FloatField()),
                ("previous_elo", models.FloatField(blank=True, null=True)),
                ("elo_change", models.FloatField(default=0.0)),
                (
                    "matches_played",
                    models.IntegerField(
                        default=0, help_text="Matches in this calculation period"
                    ),
                ),
                ("last_match_date", models.DateField(blank=True, null=True)),
                (
                    "form_rating",
                    models.FloatField(
                        blank=True, help_text="Recent form factor", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "elo_calculations",
                "ordering": ["-week", "-elo"],
                "indexes": [
                    models.Index(
                        fields=["week", "season"], name="elo_calcula_week_3ba714_idx"
                    ),
                    models.Index(
                        fields=["player_name", "week"],
                        name="elo_calcula_player__56dda7_idx",
                    ),
                    models.Index(
                        fields=["elo"], name="elo_calcula_elo_rat_5b3371_idx"
                    ),
                ],
                "unique_together": {("player_name", "week", "season")},
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Keeper", "Goalkeeper"),
                            ("Defender", "Defender"),
                            ("Midfielder", "Midfielder"),
                            ("Attacker", "Attacker"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("elo", models.FloatField(help_text="Player's Elo rating")),
                ("cost", models.FloatField(help_text="Player's cost in millions")),
                (
                    "week",
                    models.IntegerField(db_index=True, help_text="Game week number"),
                ),
                ("team", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "competition",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "players",
                "ordering": ["-elo"],
                "indexes": [
                    models.Index(
                        fields=["week", "position"], name="players_week_bd87d3_idx"
                    ),
                    models.Index(
                        fields=["week", "elo"], name="players_week_bdf28c_idx"
                    ),
                    models.Index(
                        fields=["position", "elo"], name="players_positio_5b0a51_idx"
                    ),
                ],
                "unique_together": {("name", "week")},
            },
        ),
        migrations.CreateModel(
            name="PlayerMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(db_index=True, max_length=200)),
                ("season", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("competition", models.CharField(max_length=100)),
                ("round_info", models.CharField(blank=True, max_length=100)),
                ("opponent", models.CharField(max_length=100)),
                ("result", models.CharField(max_length=20)),
                ("position", models.CharField(blank=True, max_length=50)),
                ("minutes_played", models.IntegerField(default=0)),
                ("goals", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                (
                    "elo_after_match",
                    models.FloatField(help_text="Elo rating after this match"),
                ),
                ("saves", models.IntegerField(default=0, help_text="For goalkeepers")),
                (
                    "goals_conceded",
                    models.IntegerField(
                        default=0, help_text="For goalkeepers/defenders"
                    ),
                ),
                ("clean_sheet", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "player_matches",
                "ordering": ["-date", "player_name"],
                "indexes": [
                    models.Index(
                        fields=["player_name", "date"],
                        name="player_matc_player__9260d6_idx",
                    ),
                    models.Index(
                        fields=["player_name", "season"],
                        name="player_matc_player__227239_idx",
                    ),
                    models.Index(
                        fields=["date", "competition"],
                        name="player_matc_date_1f46ea_idx",
                    ),
                    models.Index(
                        fields=["player_name", "elo_after_match"],
                        name="player_matc_player__a98021_idx",
                    ),
                ],
                "unique_together": {("player_name", "date", "opponent")},
            },
        ),
    ]
