# Generated by Django 5.2.6 on 2025-09-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_gameweek",
                    models.IntegerField(
                        default=1, help_text="Current game week number (1-38)"
                    ),
                ),
                (
                    "current_season",
                    models.CharField(
                        default="2024/25",
                        help_text="Current season (e.g., 2024/25)",
                        max_length=20,
                    ),
                ),
                (
                    "last_data_update",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time data was refreshed from FPL API",
                        null=True,
                    ),
                ),
                (
                    "last_fixtures_update",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time fixtures were updated",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
            },
        ),
    ]
