# Generated by Django 5.2.4 on 2025-09-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApi", "0002_systemsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="playermatch",
            name="elo_before_match",
            field=models.FloatField(
                default=1200.0, help_text="Elo rating before this match"
            ),
        ),
    ]
