# Generated by Django 5.2.6 on 2025-09-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApi", "0004_alter_systemsettings_current_season_playerfixture_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DifficultyMultiplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty_rating",
                    models.IntegerField(
                        help_text="FPL difficulty rating (1-5)", unique=True
                    ),
                ),
                (
                    "multiplier",
                    models.FloatField(
                        help_text="Calculated multiplier for this difficulty level"
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(
                        default=0, help_text="Number of matches used in calculation"
                    ),
                ),
                (
                    "last_calculated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this multiplier was last updated"
                    ),
                ),
            ],
            options={
                "db_table": "difficulty_multipliers",
                "ordering": ["difficulty_rating"],
            },
        ),
    ]
