# Generated by Django 5.2.6 on 2025-09-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MyApi", "0005_difficultymultiplier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="elocalculation",
            options={},
        ),
        migrations.RenameIndex(
            model_name="elocalculation",
            new_name="elo_calcula_elo_a02dfb_idx",
            old_name="elo_calcula_elo_rat_5b3371_idx",
        ),
    ]
