# Generated by Django 5.2.6 on 2025-09-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MyApi", "0007_rename_elocalculation_field"),
        ("MyApi", "00XX_remove_old_elocalculation_index"),
    ]

    operations = []
