# Generated by Django 5.2.6 on 2025-09-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApi", "0008_merge_20250922_1854"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fpl_team_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                "db_table": "teams",
                "ordering": ["fpl_team_id"],
            },
        ),
    ]
