# Generated by Django 5.2.6 on 2025-09-30 21:48

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ("MyApi", "0009_team"),
    ]

    operations = [
        migrations.AddField(
            model_name='currentsquad',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_squad', to='auth.user'),
            preserve_default=False,
        ),
    ]
