# Generated by Django 5.2.6 on 2025-10-01 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApi", "0010_add_user_to_currentsquad"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="currentsquad",
            unique_together={("user",)},
        ),
        migrations.CreateModel(
            name="UserSquad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.IntegerField(db_index=True)),
                ("name", models.CharField(default="Squad", max_length=100)),
                ("squad_data", models.TextField(default="{}")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_squads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_squad",
                "ordering": ["user", "week"],
                "unique_together": {("user", "week")},
            },
        ),
    ]
