# Generated by Django 5.2.6 on 2025-10-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApi", "0011_alter_currentsquad_unique_together_usersquad"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerfixture",
            name="projected_points",
            field=models.FloatField(
                default=0.0, help_text="Projected points for this fixture"
            ),
        ),
    ]
